name: .NET Build, Angular Build, Test and SonarQube

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install Angular CLI
        run: npm install -g @angular/cli@19

      - name: Install deps and build angular app
        run: |
          cd client
          npm install
          ng build

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "9.0"

      - name: Install SonarScanner for .NET
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "${HOME}/.dotnet/tools" >> $GITHUB_PATH

      - name: SonarQube Begin Analysis
        run: dotnet sonarscanner begin /k:"euromotors-api" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}"

      - name: Restore dependencies
        run: dotnet restore ./server/EuroMotors.sln

      - name: Build the .NET project
        run: dotnet build ./server/EuroMotors.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./server/EuroMotors.sln --configuration Release --no-restore --verbosity normal

      - name: SonarQube End Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONARQUBE_TOKEN }}"
