name: .NET Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "9.0"

      - name: Restore dependencies
        run: dotnet restore  ./server/EuroMotors.sln

      - name: Build the project
        run: dotnet build ./server/EuroMotors.sln --configuration Release --no-restore

      - name: Run tests
        run: dotnet test ./server/EuroMotors.sln --configuration Release --no-restore --verbosity normal
